project:
  type: website
  output-dir: docs

website:
  title: "Rasmus Frigaard Lemvig"
  search: false
  navbar:
    background: dark
    pinned: true
    left:
    - text: "Home"
      href: index.qmd
    - text: "Education"
      href: education.qmd
    - text: "Work experience"
      href: work.qmd
    - text: "Volunteer work"
      href: volunteer.qmd
    - text: "Projects"
      href: projects.qmd
#    - text: "Blogposts" 
#      href: blog.qmd
    - text: "About me"
      href: about.qmd 
    right:
    - icon: github
      href: https://github.com/RasmusFL
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
