---
title: "Education"
toc: false
format: 
  html:
    page-layout: full
---

### Master of Science in Actuarial Mathematics 
University of Copenhagen (November 2022 - present)

### Bachelor of Science in Actuarial Mathematics 
University of Copenhagen (September 2021 - June 2023)

### Bachelor of Science in Mathematics 
University of Copenhagen (September 2018 - June 2021)

### Technical/HTX student 
NEXT Sukkertoppen Gymnasium (2015 - 2018)

## Courses completed

Below are all university level courses that I have completed. All courses were taken at the University of Copenhagen. 

* Probability theory:
    + Stochastic Processes 3
    + Stochastic Processes 2
    + Stochastic Processes
    + Probability Theory/Measures and Integrals
    + Probability Theory and Statistics
* Statistics:
    + Semiparametric Inference
    + Statistics B
    + Statistics A
    + Regression
    + Causality
    + Mathematical Statistics
* Insurance and finance:
    + Projects in the Mathematics of Life Insurance
    + Topics in Non-Life Insurance
    + Topics in Life Insurance
    + Quantitative Risk Management
    + Introduction to Extreme Value Theory
    + Stochastic Processes in Non-Life Insurance
    + Stochastic Processes in Life Insurance
    + Accounting and Law
    + Insurance and Law
    + Basic Life Insurance Mathematics
    + Basic Non-Life Insurance Mathematics
    + Continuous Time Finance
* Analysis:
    + Complex Analysis
    + Lebesgue Integral and Measure Theory/Analysis 2
    + Analysis 1
    + Analysis 0
* Algebra and number theory:
    + Commutative Algebra
    + Homological Algebra
    + Algebra 3 (as a project outside course scope)
    + Algebra 2
    + Algebra 1
    + Introduction to Number Theory
    + Linear Algebra in the Mathematical Sciences
* Geometry and topology:
    + Algebraic Geometry 2
    + Algebraic Geometry (as a project outside course scope)
    + Geometry 2
    + Algebraic Topology
    + Topology
    + Geometry 1
* Miscellaneous:
    + Introduction to the Mathematical Sciences
    + Discrete Mathematical Methods
    + Theory of the Mathematical Sciences
    + Algorithms and Data Structures
    + Introduction to Economics
    + Introduction to Numerical Analysis

Total ECTS (including projects): 382.5
