---
title: "Projects and notes"
toc: false
format: 
  html:
    page-layout: full
---

In this tab is a collection of all projects, I find relevant to share.

### Master's thesis

My master's thesis, supervised by Martin Bladt with Niklas Pfister as co-supervisor, is titled Machine learning methods for survival and multi-state models and is available [here](Documents/project_final.pdf).

Abstract: In this thesis, we present and explore the random survival forest procedure, a machine learning algorithm for predicting the cumulative hazard from right-censored survival data. We explore the algorithm from a practical perspective by implementing the method from scratch in Julia and analysing several real datasets as well as a simulated dataset from life insurance. We furthermore investigate the theoretical properties of the algorithm by stating and proving consistency. The final part of the project concerns an extension of the random survival forest to multi-state models. We describe estimation in such a model and establish a new result on consistency for a single tree under the Markov assumption.

### Lecture notes in Quantitative Risk Management

I wrote lecture notes for the course Quantitative Risk Management during my 6th year. A second draft is [here](Documents/QRMv2.pdf). Should you want solutions to exercises or have you found typos, you are very welcome to write to me.

### A tour of the Eisenstein integers

A short note on the ring of Eisenstein integers is available [here](Documents/EI.pdf). My motivation for writing these notes is twofold. First of all, when writing my bachelor project, I swept a lot of details under the rug when implementing the algorithms for the Eisenstein integers. Second, I have not been able to find a comprehensive description of this ring online. This paper hopefully constitutes a thorough introduction.

### Lecture notes in Stochastic Processes in Non-Life Insurance
I wrote lecture notes for the course Stochastic Processes in Non-Life Insurance (abbreviated SkadeStok) during my 6th year. A first draft is [here](Documents/SkadeStok.pdf).

### (First) Bachelor's thesis
I wrote my first bachelor project in cubic and quartic reciprocity with perspectives to class field theory. My supervisor was Ian Kiming. I first present the necessary machinery needed to give elementary (but somewhat tedious) proofs of the two main theorems, namely Cubic Reciprocity and Quartic Reciprocity. Afterwards, I take a dive into Kummer theory and class field theory in order to obtain a more high level proof of cubic reciprocity. I also spent some time writing and implementing algorithms to compute the cubic and quartic residue symbols in C++. The code is found in the following repositories:

* [Gaussian integers](https://github.com/RasmusFL/GaussianIntegers)
* [Eisenstein integers](https://github.com/RasmusFL/EisensteinIntegers)

Note that in order to compile the code, you need the [GMP library](https://gmplib.org/). For many, it is likely easier to rewrite the essential algorithms in another language.

A revised version of the complete project can be found [here](Documents/project_revised.pdf). In the revised version, a few errors and typos have been corrected. The last section on class field theory likely has some errors remaining.


