---
title: "Volunteer work"
toc: false
format: 
  html:
    page-layout: full
---

## Student Representative in the Board of Education
University of Copenhagen, Department of Mathematical Sciences. We read all course and project evaluations and determine a proper categorization from these.

## [Danish Youth Association of Science/Ungdommens Naturvidenskabelige Forening (UNF)](https://unf.dk/)
I have done all sorts of work for UNF through the years. A brief overview is in my [CV](Documents/CV.pdf). Below follows a more comprehensive description. I started as a volunteer in 2016, and I am still active. A list of projects, I have been involved in, is below. Note that all attached material is in Danish.

### UNF Science Weekend/Naturfagsweekend
Science Weekend is a weekend camp for 7th - 9th graders. The project started small in 2019 (under the name Masterclass) where we had about 20 participants and just as many volunteers. The year after in 2020, the camp had grown to 65 participants and five subjects (from four the year before). Thankfully, the camp took place right before the COVID-19 lockdowns. Thanks to an extraordinary funding, we even held the camp another time in 2020, namely in the summer holidays (with restrictions of course). The following year the camp took place twice, again with 65 participants and a new name, Science Weekend. In 2022, we scaled up further to 85 participants and more than 30 volunteers along with six subjects, and again the camp was held twice. The camp was held twice in 2023 as well.

My role in the camp has evolved as follows:

* 2019: Teacher in chemistry.
* 2020: Teacher in mathematics (subject: graph theory) and assistant coordinator.
* 2021: Coordinator and teacher in mathematics (subject: number theory).
* 2022: Coordinator and teacher in mathematics (subject: graph theory version 2).
* 2023: Coordinator and teacher in mathematics (subject: set theory and probability theory).

For those interested, the material from the camps are below:

* [2019 Material](UNF/Camps/Kompendium2019.pdf)
* [2020 Material (first camp)](UNF/Camps/Kompendium2020_1.pdf)
* [2020 Material (second camp, minor changes and corrections)](UNF/Camps/Kompendium2020_2.pdf)
* [2021 Material](UNF/Camps/Kompendium2021.pdf)
* [2022 Material](UNF/Camps/Kompendium2022.pdf)
* [2023 Material](UNF/Camps/Kompendium2023.pdf)

### UNF Mathematics Camp

UNF Mathematics Camp has been held since 2007 and is but one of many UNF summer camps. In fact, a (Danish) [Wikipedia article](https://da.wikipedia.org/wiki/ScienceCamps) is dedicated to keeping track of them. My role in the project is as follows:

* 2020 (cancelled due to COVID-19): Assistant teacher.
* 2021: Assistant teacher.
* 2022: Teacher (subject: probability theory).
* 2023: Teacher (subject: applied linear algebra).
* 2024: Teacher (subject: ring theory).

I took part in writing the material in 2022, 2023 and 2024. The material for the 2022 camp is [here](UNF/Camps/MatCamp2022.pdf). The material for the 2023 camp is [here](UNF/Camps/MatCamp2023.pdf). The material for 2024 will be made available in the near future.

### Lectures

I have helped as a volunteer in many evening lectures in UNF. I have also arranged a number of lectures in mathematics.

### Workshops

I have taught several workshops in mathematics. A list is below:

* Differential calculus: [Material](UNF/Workshops/Differentialregning-intro.pdf), [presentation](UNF/Workshops/DifferentialregningBeamer.pdf)
* Integral calculus: [Material](UNF/Workshops/Integralregning-intro.pdf), [presentation](UNF/Workshops/IntegralregningBeamer.pdf)
* Differential equations: [Material](UNF/Workshops/Workshop_om_differentialligninger.pdf), [presentation](UNF/Workshops/DifferentialligningerBeamer.pdf)
* Linear algebra: [Material](UNF/Workshops/LinAlg-intro.pdf), [presentation](UNF/Workshops/LineærAlgebraBeamer.pdf)
* Series and sequences: [Material](UNF/Workshops/Workshop_om_følger_og_rækker.pdf), [presentation](UNF/Workshops/FølgerOgRækkerBeamer.pdf)
* Number theory: [Material](UNF/Workshops/Talteori-intro.pdf), [presentation](UNF/Workshops/TalteoriBeamer.pdf)
* Graph theory: [Material](UNF/Workshops/Grafteori-intro.pdf), [presentation](UNF/Workshops/GrafteoriBeamer.pdf)
* Vectors and parametrized curves:  [Material](UNF/Workshops/Vektorer_og_vektorfunktioner-intro.pdf), [presentation](UNF/Workshops/Vektorer_og_vektorfunktionerBeamer.pdf)

### Evenings of Natural Science Education

From May to September 2022, I took part in teaching young Ukrainian refugees in Copenhagen. I also did some of the administrative work.

### Miscellaneous

I had the role of secretary in the local branch UNF Copenhagen from July 2020 to March 2021. I was night watchman at Chemistry Camp 2019 and Computer Science Camp 2023.

