---
title: "Work experience"
toc: false
format: 
  html:
    page-layout: full
---

### Teaching assistant
at the University of Copenhagen, Department of Mathematical Sciences (September 2020 - present). My teaching history (in order from latest to earliest) is as follows:

* 2024/2025
  + Topics in Probability
  + Brownian Motion
  + BrushUp course in mathematics for biochemistry
  + Study Café

* 2023/2024
  + BrushUp course in mathematics + BrushUp for biochemistry
  + Lebesgue Integral and Measure Theory
  + Stochastic Processes in Non-Life Insurance
  + Advanced Probability Theory 2
  + Continuous Time Finance
  + Analysis 0
  + Insurance and Law
  + Study Café

* 2022/2023
  + BrushUp course in mathematics
  + Lebesgue Integral and Measure Theory
  + Probability Theory
  + Analysis 0
  + Probability Theory 2
  + Insurance and Law
  + Study Café
  
* 2021/2022
  + Discrete Mathematical Methods
  + Linear Algebra in the Mathematical Sciences
  + Analysis 0
  + Study Café

* 2020/2021
  + Introduction to the Mathematical Sciences
  + Linear Algebra in the Mathematical Sciences
  + Geometry 1
  + Study Café

### Freelance Tutor at GoTutor 
I mostly taught mathematics, but occasionally also other subjects (2019 - 2020).

### Mathematics Tutor
I have worked as a self-employed tutor for several students (September 2021 - present). 
